### ISSUE TITLE
大小写不匹配的问题

### ISSUE THREAD

**Issue by 18ccc** [chr233/ASFProfileConverter#2]
mafile文件里的account_name是默认小写的，所以有的账号里带有大写字母的话，就不会匹配。所以这个建议更改一下，大写ID也可以匹配mafile文件的账号小写，然后输出的格式账号ID为大写的

**Comment by chr233** [comment]
了解

**Comment by chr233** [comment]
你更新一下试试，大小写的问题我记得之前已经修好了

**Comment by chr233** [comment]
已修复

**Comment by 18ccc** [comment]
好样的！
